import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { AuthProvider } from "./Providers";
import { UserProvider } from "@/components/UserContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SW-blogs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <UserProvider>
            <Navbar />
            {children}{" "}
          </UserProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
